[package]
name = "02_hyper"
version = "0.1.0"
authors = ["my name <my@email.address>"]

[dependencies]
futures = "0.1"
hyper = "0.12"
hyper-rustls = "0.16"
tokio = "0.1"

[dependencies.kitsu]
default-features = false
features = ["hyper-support"]
path = "../../"
